apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awesome-cats-cert
spec:
  secretName: awesome-cats-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: aiasv.dev
  dnsNames:
  - aiasv.dev