apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-cats-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awesome-cats-frontend
  template:
    metadata:
      labels:
        app: awesome-cats-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/engaged-droplet-426007-b5/awesome_cats_frontend:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: awesome-cats-frontend
  ports:
    - port: 80
      targetPort: 80